import:
#- ~/.config/alacritty/catppuccin-mocha.toml

## env vars
env:
 TERM: xterm-256color

## window settings
window:
  opacity: 0.9
  padding:
    x: 15
    y: 15

# Class (window name)
class:
  instance: Alacritty
  general: Alacritty
