#! /bin/sh
#===========================================================================
#
#
#███╗   ███╗ █████╗ ██████╗ ██╗ ██████╗ ██████╗ ██████╗  ██████╗ ███╗   ███╗
#████╗ ████║██╔══██╗██╔══██╗██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗████╗ ████║
#██╔████╔██║███████║██████╔╝██║██║   ██║██████╔╝██████╔╝██║   ██║██╔████╔██║
#██║╚██╔╝██║██╔══██║██╔══██╗██║██║   ██║██╔══██╗██╔══██╗██║   ██║██║╚██╔╝██║
#██║ ╚═╝ ██║██║  ██║██║  ██║██║╚██████╔╝██║  ██║██║  ██║╚██████╔╝██║ ╚═╝ ██║
#╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═╝ ╚═╝ ╚═╝ ╚═════╝ ╚═╝     ╚═╝                                                                          
#                          MarioRRom's Dotfiles
#                 https://github.com/MarioRRom/bspwm-dotfiles
#===========================================================================


## Scripts
PATH="$HOME/.config/bspwm/scripts:$PATH"

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

## Workspaces
workspaces() {
    name=1
    for monitor in $(bspc query -M); do
        bspc monitor "${monitor}" -n "$name" -d '1' '2' '3' '4' '5' '6'
        ((name++))
    done
}

workspaces

## Decorations
bspc config border_width         2
bspc config active_border_color "#45475a"
bspc config focused_border_color "#89dceb"
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config single_monocle true
bspc config borderless_monocle false
bspc config gapless_monocle false

## Mouse Configuration
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
xsetroot -cursor_name left_ptr &

## Windows Rules
bspc rule -a steam state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a burp-StartBurp: state=floating

## Process on Startup

processes=("picom" "polybar" "sxhkd" "dunst" "nitrogen")

for process in "${processes[@]}"; do
  if pidof -q "$process"; then
    pkill -9 -x "$process" > /dev/null; sleep 0.1
  fi
done


sxhkd -c ~/.config/bspwm/keys &

picom --config ~/.config/bspwm/picom.conf & 

## Lanzar polybar en cada monitor
if type "xrandr"; then
    for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
        MONITOR=$m polybar --reload -c ~/.config/bspwm/polybar/top_bar.ini &
    done
else
    polybar --reload -c ~/.config/bspwm/polybar/top_bar.ini &
fi

# Set Wallpaper
nitrogen --restore &

dunst -config ~/.config/bspwm/notifications &

## Iniciar Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#Xresources
xrdb merge "$HOME"/.Xresources &

# Buscar Actualizaciones
while true;do
    ~/.config/bspwm/scripts/Updates
    sleep 300 # esperar 5 minutos antes de ejecutar nuevamente
done &