#! /bin/sh
#===========================================================================
#
#
#███╗   ███╗ █████╗ ██████╗ ██╗ ██████╗ ██████╗ ██████╗  ██████╗ ███╗   ███╗
#████╗ ████║██╔══██╗██╔══██╗██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗████╗ ████║
#██╔████╔██║███████║██████╔╝██║██║   ██║██████╔╝██████╔╝██║   ██║██╔████╔██║
#██║╚██╔╝██║██╔══██║██╔══██╗██║██║   ██║██╔══██╗██╔══██╗██║   ██║██║╚██╔╝██║
#██║ ╚═╝ ██║██║  ██║██║  ██║██║╚██████╔╝██║  ██║██║  ██║╚██████╔╝██║ ╚═╝ ██║
#╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚═╝     ╚═╝                                                                          
#                          MarioRRom's Dotfiles
#
#===========================================================================

## Load Monitor configuration of arandr
~/.screenlayout/monitors.sh &

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

## Workspaces
bspc monitor VGA-0 -d I II III IV V
bspc monitor HDMI-0 -d I

## Decorations
bspc config border_width         2
bspc config active_border_color "#45475a"
bspc config focused_border_color "#89dceb"
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

## Mouse Configuration
#bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
xsetroot -cursor_name left_ptr &

## Windows Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a burp-StartBurp: state=floating

## Process on Startup

processes=("picom" "polybar" "sxhkd" "dunst" "komorebi")

for process in "${processes[@]}"; do
  if pidof -q "$process"; then
    pkill -9 -x "$process" > /dev/null; sleep 0.1
  fi
done


sxhkd -c ~/.config/bspwm/keys &

picom --config ~/.config/bspwm/picom.conf & 

## Lanzar polybar en cada monitor
if type "xrandr"; then
    for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
        MONITOR=$m polybar --reload -c ~/.config/bspwm/polybar/top_bar.ini &
    done
else
    polybar --reload -c ~/.config/bspwm/polybar/top_bar.ini &
fi

komorebi &

dunst -config ~/.config/bspwm/notifications &

## Iniciar Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#Xresources
xrdb merge "$HOME"/.Xresources &

