#!/bin/bash
#===========================================================================
#
#
#███╗   ███╗ █████╗ ██████╗ ██╗ ██████╗ ██████╗ ██████╗  ██████╗ ███╗   ███╗
#████╗ ████║██╔══██╗██╔══██╗██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗████╗ ████║
#██╔████╔██║███████║██████╔╝██║██║   ██║██████╔╝██████╔╝██║   ██║██╔████╔██║
#██║╚██╔╝██║██╔══██║██╔══██╗██║██║   ██║██╔══██╗██╔══██╗██║   ██║██║╚██╔╝██║
#██║ ╚═╝ ██║██║  ██║██║  ██║██║╚██████╔╝██║  ██║██║  ██║╚██████╔╝██║ ╚═╝ ██║
#╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═╝ ╚═╝ ╚═╝ ╚═════╝ ╚═╝     ╚═╝                                                                          
#                          MarioRRom's Dotfiles
#                 https://github.com/MarioRRom/bspwm-dotfiles
#===========================================================================

## ESTE SCRIPT INICIA TODAS LAS APPS QUE CONTENGAS EN TU CARPETA UBICADA  ##
##  EN .config/autostart PERMITIENDO LA EJECUCION AUTOMATICA DE TUS APPS  ##


# Comprobar si dex está instalado
if ! command -v dex &> /dev/null; then
    notify-send "dex no está instalado. Por favor, instálalo para continuar."
    exit 1
fi


#  .-------------------------.
#  | .---------------------. |
#  | | Lanzar Aplicaciones | |
#  | `---------------------' |
#  `-------------------------'

for file in ~/.config/autostart/*.desktop; do
    # Verifica si el archivo tiene la clave Hidden=true para ignorarlo
    if grep -q "Hidden=true" "$file"; then
        continue
    fi

    # Obtiene el comando de ejecución desde el archivo .desktop
    exec_command=$(grep -i "^Exec=" "$file" | cut -d'=' -f2)

    # Verifica si la aplicación ya está corriendo
    if pgrep -f "$exec_command" > /dev/null; then
        continue
    fi

    # Ejecuta los comandos asociados al archivo .desktop
    dex "$file" &
done