#!/bin/bash
#===========================================================================
#
#
#███╗   ███╗ █████╗ ██████╗ ██╗ ██████╗ ██████╗ ██████╗  ██████╗ ███╗   ███╗
#████╗ ████║██╔══██╗██╔══██╗██║██╔═══██╗██╔══██╗██╔══██╗██╔═══██╗████╗ ████║
#██╔████╔██║███████║██████╔╝██║██║   ██║██████╔╝██████╔╝██║   ██║██╔████╔██║
#██║╚██╔╝██║██╔══██║██╔══██╗██║██║   ██║██╔══██╗██╔══██╗██║   ██║██║╚██╔╝██║
#██║ ╚═╝ ██║██║  ██║██║  ██║██║╚██████╔╝██║  ██║██║  ██║╚██████╔╝██║ ╚═╝ ██║
#╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝ ╚═════╝ ╚═╝  ╚═╝ ╚═╝ ╚═╝ ╚═════╝ ╚═╝     ╚═╝                                                                          
#                          MarioRRom's Dotfiles
#                 https://github.com/MarioRRom/bspwm-dotfiles
#===========================================================================

# Iconos y colores
iDIR="$HOME/.config/bspwm/assets"
notify_cmd='dunstify -u low -h string:x-dunst-stack-tag:obbrightness'
icon="$iDIR/brightness.svg"

# Obtener el brillo actual
get_brightness() {
    brightnessctl get
}

# Obtener el brillo máximo
get_max_brightness() {
    brightnessctl max
}

# Calcular porcentaje de brillo
get_brightness_percentage() {
    current=$(get_brightness)
    max=$(get_max_brightness)
    echo $((current * 100 / max))
}

# Generar barra de brillo
get_brightness_bar() {
    brightness=$(get_brightness_percentage)
    filled=$((brightness / 10))
    empty=$((10 - filled))

    bar=""
    for i in $(seq 1 $filled); do
        bar="${bar}━"
    done
    for i in $(seq 1 $empty); do
        bar="${bar}─"
    done

    echo "$bar"
}

# Notificar al usuario
notify_user() {
    ${notify_cmd} -i "$icon" "$(get_brightness_bar)"
}

# Aumentar el brillo
inc_brightness() {
    brightnessctl set +10% && notify_user
}

# Disminuir el brillo
dec_brightness() {
    brightnessctl set 10%- && notify_user
}

# Ajustar el brillo a un valor específico
set_brightness() {
    brightnessctl set "$1%"
}

# Ejecutar
if [ -x $(which brightnessctl) ]; then
    if [[ "$1" == "--get" ]]; then
        get_brightness_percentage
    elif [[ "$1" == "--aum" ]]; then
        inc_brightness
    elif [[ "$1" == "--baj" ]]; then
        dec_brightness
    elif [[ "$1" == "--set" && -n "$2" ]]; then
        set_brightness "$2"
    else
        echo "$(get_brightness_bar)"
    fi
else
    ${notify_cmd} "'brightnessctl' no está instalado."
fi